install.packages("readxl")
install.packages("ggplot2")

library(readxl)
w201501 <- read_excel("R_Data/airport 2015/w201501.xls")
w201502 <- read_excel("R_Data/airport 2015/w201502.xls")
w201503 <- read_excel("R_Data/airport 2015/w201503.xls")
w201504 <- read_excel("R_Data/airport 2015/w201504.xls")
w201505 <- read_excel("R_Data/airport 2015/w201505.xls")
w201506 <- read_excel("R_Data/airport 2015/w201506.xls")
w201507 <- read_excel("R_Data/airport 2015/w201507.xls")
w201508 <- read_excel("R_Data/airport 2015/w201508.xls")
w201509 <- read_excel("R_Data/airport 2015/w201509.xls")
w201510 <- read_excel("R_Data/airport 2015/w201510.xls")
w201511 <- read_excel("R_Data/airport 2015/w201511.xls")
w201512 <- read_excel("R_Data/airport 2015/w201512.xls")

library(ggplot2)

ggplot(w201501, aes(x=요일, y=합계,group=1))+ggtitle("2015년 1월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201502, aes(x=요일, y=합계,group=1))+ggtitle("2015년 2월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201503, aes(x=요일, y=합계,group=1))+ggtitle("2015년 3월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201504, aes(x=요일, y=합계,group=1))+ggtitle("2015년 4월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201505, aes(x=요일, y=합계,group=1))+ggtitle("2015년 5월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201506, aes(x=요일, y=합계,group=1))+ggtitle("2015년 6월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201507, aes(x=요일, y=합계,group=1))+ggtitle("2015년 7월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201508, aes(x=요일, y=합계,group=1))+ggtitle("2015년 8월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201509, aes(x=요일, y=합계,group=1))+ggtitle("2015년 9월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201510, aes(x=요일, y=합계,group=1))+ggtitle("2015년 10월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201511, aes(x=요일, y=합계,group=1))+ggtitle("2015년 11월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
ggplot(w201512, aes(x=요일, y=합계,group=1))+ggtitle("2015년 12월")+geom_line()+geom_line(aes(x=요일, y=출발), colour="red")+geom_line(aes(x=요일,y=도착),colour="blue")+geom_point()+geom_point(aes(x=요일,y=출발),colour="red")+geom_point(aes(x=요일,y=도착),colour="blue")
